builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    binaries:
      - gojira
    image_templates:
      - "leozhantw/gojira:latest"
      - "leozhantw/gojira:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
brews:
  -
    name: gojira
    tap:
      owner: leozhantw
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/leozhantw/gojira"
    description: "Save your time on Jira operation through the command line."
    license: "MIT"
